### ISSUE TITLE
Possible small bug in the dtm software?

### ISSUE THREAD

**Issue by Xiangju** [blei-lab/dtm#1]
Hello, 

   Many thanks for making the Dynamic Topic Model software opensource to the public.

   I'm using DTM to analyze my time-varying dataset, and want to compare the held-out loglikelihood of DTM and my model on the test dataset.

   However, it seems there is a small bug in the DTM software which makes the software unable to run in --mode=time on my ubuntu computer. The error information is as follows:

```
gsl: ../gsl/gsl_vector_double.h:193: ERROR: index out of range
Default GSL error handler invoked.
Aborted (core dumped)
```

   I'm not sure there is anyone who has ever run the software successfully in --mode=time into to obtain held-out log likelihood?

   I did some debugging on the software, and find the source of the bug/error: 

   source file: lda.c

   double compute_lda_lhood(lda_post\* p) {
      int k, n;
      int K = p->model->ntopics, N = p->doc->nterms;

```
  double gamma_sum = sum(p->gamma);
  double lhood =
    gsl_sf_lngamma(sum(p->model->alpha)) -
    gsl_sf_lngamma(gamma_sum);

  vset(p->lhood, K, lhood); // This is line cause the error. It seems the bug is reasonable because the indices of the vector array for p->lhood start from 0 to K-1 

  .........

}
```

   I wonder whether this line (vset(p->lhood, K, lhood);) is necessary or not? Will it affect the fininal log likelihood if I remove this line? The software can run in --mode=time successfully if I remove/comment this line. If this line is necessary, how can I fix the bug so that the software can run in --mode=time successfully?

   It seems to me this line is not necessary, because after this line, you have a for loop to calculate the log likelihood for each topic:

   for (k = 0; k < K; k++) {
        .............
    vset(p->lhood, k, lhood_term);
    lhood += lhood_term;
    lhood += influence_term;

   }

   Thanks for checking this bug!

A loytal user of the DTM software

**Comment by jaanaltosaar** [comment]
Thanks Xiangju - can you submit a pull request commenting out these lines?
