### ISSUE TITLE
How to use the parallel version?

### ISSUE THREAD

**Issue by xiaoleihuang** [blei-lab/dtm#16]
I've tried to compile the dtm-parallel, but I did not find the generated main file like the non-parallel version.

**Comment by nathan-h-le** [comment]
> I've tried to compile the dtm-parallel, but I did not find the generated main file like the non-parallel version.

Did you have the solution?

**Comment by xiaoleihuang** [comment]
@le-hoang-nhan It has been for a while. I don't think I solved the problem. I guess the codes was designed for a couple of computers...

**Comment by ashutosh29** [comment]
dtm-parellel is written for cluster of computers rather than using multiprocessing. It is mentioned here 

https://github.com/blei-lab/dtm/tree/master/dtm-parallel
